# Copyright contributors to the IBM Security Verify Access Operator project

# permissions for end users to view ibmsecurityverifyaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmsecurityverifyaccess-viewer-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifyaccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifyaccesses/status
  verbs:
  - get
